language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # FIREBASE_TOKEN
    - secure: da2q6LD3fPITtyApqil52kmSHj/GsaZok/e0ezxjD+xoxVhsYJEd0ABgPVua9cujMUFJwTea3htqjbgKbo7CDKXvCBOEDSA2dR2WspRRkaQK1b111N1EqZF0KEa3jpH3X0WZT1OSly18g/tXtIM6a/J8usXSX3MWfPYi+JHnBlrp0PO379VpMz2YwXpo/VcvesGkFinwAlHafAKJw/d1PuF41Ch8CUabBREDDsPK1F03PEX4eYiRtXGKWU2LOF7etUthagdEUvqrL4yxVVBnyGDE+AlT13RPyFUKJwMPwnhAkrTEv+KqMdLZUTbNpB2vlAAoigOGyevp2DBFQz7qYiyRp8SbTa3bHAl+uD+mC5+unSx3FRSEV7XPFE25Y1pgxzIBkk5bygRrQktzt2sYoz4pP5TCu/fb7EligM+/XDL5fqpxACurUXxySuqYUFBb+Pb8QPQlDlMfH4WaDS+TnW1JO/L3y6/J9sUBZ/P5Wz+b79ZWb6JX18fYhbWXyFCEfj/8dIi9GnrOVwF/KV+qc6Yt067cDnIvwF/sf8UA9FaVi50fPFOqxo3oloNygPZNRvKOfYVA0c7QgViXr4ICTqQ5zC6MsHk6X2/HEPnKbnNGVvd8cWFshDkskSSRW8sakRClPqLhacaD0soPN2btQnejEgdBnvQgU6lHACax8TQ=
    # FIREBASE_SECRET
    - secure: VFzHD1AHtoEExYYHKoZ1anc6joX3+b63961bGDaS0tS6V0+mh5R3EWw1KO+B1B8LqoeFERt+u6wAJl/PG8OFRJAWTAhV/QvnTYd9XOQZLuRiCdmqwSBFdJGo2/HxPyEIjDo8mX5ROAWB35Addl/V6FstUYgQ+0HehsYgt27k5bmK8SH/R6qYBerL8ZgKmEvY34L1tY+rzaSMhEt2JgXHqqQSiPlcExqZk+YnH1xhvLvuCedj7XYYjeSoPS0Ii3g7ak7Vs/Xod1JetXPwcGWZY8jX5oyet4wAy88VnoVdD0h0KqSh3nU6ykNRpg4C89m7P6pk2WA47oX9dZUJYb6p7VLc0XRyUnwQOTxjXFopEi2H+bP3fZL1/NEJa9ZW3jzVPBBOnlUfNpa19b26HuFGKyXtH3LeZCImyZ3DMx7p7PFZ6mNufaHJ8vYDVCcgvpIvdjT6wvT15EHrLXYQwDJKSZPSMPYjmK/n5JhFHNZANvgUF/dDHNuB0bfeoW23TXKENvce55KSc7wCxoqYmaw/LCbwK/LUUcfLfV8QFb3hWIa8PQMMF6Klaidx5z786oGR+3ut/7yZ6C82/w13QEeoQ20t6v/Hjuw3BUuD2M2vlWvCOb9yQR5UssyeBIAwr5xWbpnVR1SEj9+H2WurrJSt0GQnu7LbH8JTT2uxypTR+aY=
